language: go

go:
  - 1.13.x

script:
  - make test
  - make build

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "terraform-provider-liquidweb"
  skip_cleanup: true
  on:
    tags: true
